import { Inter } from "next/font/google";
import "./globals.css";
import DarkModeStyles from "@/components/DarkStyle";
import TemplateStyle from "@/components/TemplateStyle";
import Siderbarmenu from "@/components/Siderbarmenu";
import Menuscroll from "@/components/menuscroll";
import LeftSidebar from "@/components/LeftSidebar";
import Main from "@/components/Main";
import Nope from "@/components/Nope";
import Lightbox from "@/components/lightbox";
// import {useState} from "react"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Jhon portfolio</title>
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com/"
          crossOrigin=""
        />
        <link rel="stylesheet" href="./css/app.css" />

        <link href="./css/css2.css" rel="stylesheet" />
        <link href="./css/line-awesome.min.css" rel="stylesheet" />

        <link href="./css/fontawesome-free-6.5.2-web/css/fontawesome.min.css" />

        <link
          href="./css/fontawesome-free-6.5.2-web/css/all.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="./css/bootstrap.min.css"/>
        <link rel="stylesheet" href="./css/owl.carousel.min.css" />
        <link rel="stylesheet" href="./css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="./css/animate.min.css" />
        <link rel="stylesheet" href="./css/smooth-scrollbar.css" />
        <link rel="stylesheet" href="./css/lightbox.min.css" />

        <link rel="stylesheet" href="./css/style.css" />
        <link rel="stylesheet" href="./css/responsive.css" />

        <script src="./js/jquery.js"></script>
        <script src="./js/bootstrap.bundle.min.js"></script>
        <script src="./js/owl.carousel.js"></script>
        <script src="./js/gsap.min.js"></script>
        <script src="./js/ScrollTrigger.min.js"></script>
        <script src="./js/ScrollToPlugin.min.js"></script>
        <script src="./js/lightbox.min.js"></script>

        <script src="./js/main.js"></script>
        <script src="./js/ajax-form.js"></script>
        <script src="./js/color.js"></script>

        <style id="monica-reading-highlight-style">
          {`.monica-reading-highlight {
        animation: fadeInOut 1.5s ease-in-out;
      }

      @keyframes fadeInOut {
        0%,
        100% {
          background-color: transparent;
        }
        30%,
        70% {
          background-color: rgba(2, 118, 255, 0.2);
        }
      }`}
        </style>

        <DarkModeStyles />
      </head>
      <body
        style={{}}
        monica-version="5.2.4"
        monica-id="ofpnmcalabcbjgholdjcjblkibolbppb"
        className={inter.className}
      >
        {children}

        <TemplateStyle />

        <Siderbarmenu />

        <Menuscroll />

        <LeftSidebar />

        <Main />

        <Nope />

        <Lightbox />
      </body>
    </html>
  );
}
